=== kaybrian/xml_course_work/ XML Schema/hotels.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hotels">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hotel">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:integer"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="star">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="5"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element> 
                            <xs:element name="Facilities">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Internet"/>
                                        <xs:enumeration value="Gym"/>
                                        <xs:enumeration value="Parking"/>
                                         <xs:enumeration value="Restaurant"/>
                                          <xs:enumeration value="Pick-up"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element> 
                            <xs:element name="Address" type="xs:string"/>
                            <xs:element name="Distance" type="xs:decimal"/>
                            <xs:element name="Available">
                            <xs:simpleType>
                                <xs:restriction base="xs:boolean">
                                    <xs:enumeration value="True"/>
                                    <xs:enumeration value="False"/>
                                </xs:restriction>
                            </xs:simpleType>
                            </xs:element> 
                        </xs:sequence>
                    </xs:complexType>
                </xs:element >
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kaybrian/xml_course_work/ XML Schema/Exercise3.xml
<?xml version="1.0"?>

<hotels  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hotels.xsd">
    <hotel>
        <ID>1</ID>
        <name>Golden Tulip Little Palace</name>
        <star>7</star>
        <Facilities>
                Internet,
                Gym,
                Parking,
                Restaurant
        </Facilities>
        <Address>74 rue Amelot, Paris, 75011</Address>
        <Distance>2</Distance>
        <Available>True</Available>
    </hotel>
     <hotel>
        <ID>2</ID>
        <name> 	Les Jardins du Marais</name>
        <star>3</star>
        <Facilities>Internet</Facilities>
        <Address>4 rue Salomon De Caus, Paris, 75003</Address>
        <Distance>0.1</Distance>
        <Available> False</Available>
    </hotel>
    <hotel>
        <ID>3</ID>
        <name> 	Tilsitt Etoile</name>
        <star>2</star>
        <Facilities>Restaurant</Facilities>
        <Address> 23 rue Brey, Paris, 75017 </Address>
        <Distance>3</Distance>
        <Available> False</Available>
    </hotel>
    <hotel>
        <ID>4</ID>
        <name> Hotel Saint Charles</name>
        <star>3</star>
        <Facilities>Parking </Facilities>
        <Address>6 rue de Iâ€™Esperance, Paris, 75013 </Address>
        <Distance>1</Distance>
        <Available>True</Available>
    </hotel>
</hotels>
